package greenhousesimulator.ui;

import greenhousesimulator.Greenhouse;
import greenhousesimulator.GreenhouseDatabase;
import greenhousesimulator.Plant;
import greenhousesimulator.PlantGrowthThread;
import greenhousesimulator.Player;
import greenhousesimulator.WeatherThread;
import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;

public class GameWindow extends JFrame {
    private Greenhouse greenhouse;
    private Player player;
    private PlantGrowthThread growthThread;
    private WeatherThread weatherThread;
    
    private JLabel dayLabel;
    private JLabel moneyLabel;
    private JLabel tempLabel;
    private JLabel humidityLabel;
    private JLabel plantCountLabel;
    
    private JTextArea logArea;
    private DefaultListModel<String> plantListModel;
    private JList<String> plantList;
    
    private DefaultListModel<String> inventoryListModel;
    private JList<String> inventoryList;
    
    private Timer guiUpdateTimer;
    private boolean gameOver = false;
    
    private MainFrame mainFrame;

    public GameWindow(String playerName, MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        this.player = new Player(playerName);
        this.player.setGameWindow(this);
        this.greenhouse = new Greenhouse();
        this.greenhouse.setGameWindow(this);

        setupUI();

        growthThread = new PlantGrowthThread(greenhouse, this);
        weatherThread = new WeatherThread(greenhouse, this);

        startGameThreads();
        startGuiUpdater();
    }

    public GameWindow(String playerName, GreenhouseDatabase.SaveData saveData, MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        this.player = new Player(playerName);
        this.player.setGameWindow(this);
        this.greenhouse = new Greenhouse();
        this.greenhouse.setGameWindow(this);

        this.greenhouse.setDay(saveData.day);
        this.greenhouse.addMoney(saveData.money - 1000);
        this.greenhouse.setTemperature(saveData.temperature);
        this.greenhouse.setHumidity(saveData.humidity);

        for (Plant plant : saveData.plants) {
            this.greenhouse.addPlant(plant);
        }

        this.player.getInventory().clear();
        for (String item : saveData.inventory) {
            this.player.getInventory().add(item);
        }

        setupUI();

        growthThread = new PlantGrowthThread(greenhouse, this);
        weatherThread = new WeatherThread(greenhouse, this);

        startGameThreads();
        startGuiUpdater();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setupUI() {
        setTitle("Тепличный симулятор - Игрок: " + player.getName());
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLayout(new BorderLayout());
        setSize(1100, 700);
        setLocationRelativeTo(null);
        
        JPanel infoPanel = createInfoPanel();
        add(infoPanel, BorderLayout.NORTH);
        
        JPanel centerPanel = createCenterPanel();
        add(centerPanel, BorderLayout.CENTER);
        
        JPanel controlPanel = createControlPanel();
        add(controlPanel, BorderLayout.EAST);
        
        JPanel logPanel = createLogPanel();
        add(logPanel, BorderLayout.SOUTH);
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                exitToMenu();
            }
        });
    }
    
    private JPanel createInfoPanel() {
        JPanel panel = new JPanel(new GridLayout(2, 4, 10, 5));
        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panel.setBackground(new Color(240, 240, 240));
        
        dayLabel = createInfoLabel("День:", "1");
        moneyLabel = createInfoLabel("Деньги:", "1000 руб.");
        tempLabel = createInfoLabel("Температура:", "22°C");
        humidityLabel = createInfoLabel("Влажность:", "60%");
        plantCountLabel = createInfoLabel("Растений:", "0");
        
        panel.add(dayLabel);
        panel.add(moneyLabel);
        panel.add(tempLabel);
        panel.add(humidityLabel);
        panel.add(plantCountLabel);
        
        JButton speedButton = new JButton("След. день");
        speedButton.setFont(new Font("Arial", Font.BOLD, 14));
        speedButton.addActionListener(e -> forceNextDay());
        panel.add(speedButton);
        
        JButton saveButton = new JButton("Сохранить");
        saveButton.setFont(new Font("Arial", Font.BOLD, 14));
        saveButton.addActionListener(e -> saveGame());
        panel.add(saveButton);
        
        return panel;
    }
    
    private JLabel createInfoLabel(String title, String value) {
        JLabel label = new JLabel("<html><b>" + title + "</b> " + value + "</html>");
        label.setFont(new Font("Arial", Font.PLAIN, 14));
        return label;
    }
    
    private JPanel createCenterPanel() {
        JPanel panel = new JPanel(new BorderLayout());
        panel.setBorder(BorderFactory.createTitledBorder(
            BorderFactory.createLineBorder(Color.GRAY),
            "Растения в теплице",
            TitledBorder.CENTER,
            TitledBorder.TOP,
            new Font("Arial", Font.BOLD, 14)
        ));
        
        plantListModel = new DefaultListModel<>();
        plantList = new JList<>(plantListModel);
        plantList.setFont(new Font("Monospaced", Font.PLAIN, 12));
        plantList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        JScrollPane scrollPane = new JScrollPane(plantList);
        scrollPane.setPreferredSize(new Dimension(550, 300));
        panel.add(scrollPane, BorderLayout.CENTER);
        
        JPanel plantButtons = new JPanel(new FlowLayout());
        JButton waterButton = new JButton("Полить все");
        JButton fertilizeButton = new JButton("Удобрить все");
        JButton harvestButton = new JButton("Собрать урожай");
        JButton removeDeadButton = new JButton("Убрать погибшие");
        
        waterButton.addActionListener(e -> waterAllPlants());
        fertilizeButton.addActionListener(e -> fertilizeAllPlants());
        harvestButton.addActionListener(e -> harvestAll());
        removeDeadButton.addActionListener(e -> greenhouse.removeDeadPlants());
        
        plantButtons.add(waterButton);
        plantButtons.add(fertilizeButton);
        plantButtons.add(harvestButton);
        plantButtons.add(removeDeadButton);
        
        panel.add(plantButtons, BorderLayout.SOUTH);
        
        return panel;
    }
    
    private JPanel createControlPanel() {
        JPanel panel = new JPanel(new BorderLayout());
        panel.setBorder(BorderFactory.createTitledBorder("Управление"));
        panel.setPreferredSize(new Dimension(280, 0));
        
        JTabbedPane tabbedPane = new JTabbedPane();
        
        JPanel plantTab = createPlantTab();
        tabbedPane.addTab("Посадка", plantTab);
        
        JPanel shopTab = createShopTab();
        tabbedPane.addTab("Магазин", shopTab);
        
        JPanel inventoryTab = createInventoryTab();
        tabbedPane.addTab("Инвентарь", inventoryTab);
        
        panel.add(tabbedPane, BorderLayout.CENTER);
        
        JButton exitButton = new JButton("Выйти в меню");
        exitButton.setFont(new Font("Arial", Font.BOLD, 14));
        exitButton.setBackground(new Color(231, 76, 60));
        exitButton.setForeground(Color.BLACK);
        exitButton.addActionListener(e -> exitToMenu());
        
        panel.add(exitButton, BorderLayout.SOUTH);
        
        return panel;
    }
    
    private JPanel createPlantTab() {
        JPanel panel = new JPanel(new GridLayout(5, 1, 5, 10));
        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        String[] plants = {"Помидор (50 руб.)", "Огурец (40 руб.)", 
                          "Перец (70 руб.)", "Салат (30 руб.)"};
        String[] plantTypes = {"Помидор", "Огурец", "Перец", "Салат"};
        int[] costs = {50, 40, 70, 30};
        
        for (int i = 0; i < plants.length; i++) {
            final int index = i;
            JButton button = new JButton(plants[i]);
            button.addActionListener(e -> plantSeed(plantTypes[index], costs[index]));
            panel.add(button);
        }
        
        return panel;
    }
    
    private JPanel createShopTab() {
        JPanel panel = new JPanel(new GridLayout(6, 1, 5, 10));
        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        String[] items = {
            "Семена помидора - 50 руб.",
            "Семена огурца - 40 руб.",
            "Семена перца - 70 руб.",
            "Семена салата - 30 руб.",
            "Удобрение - 30 руб.",
            "Система полива - 200 руб."
        };
        
        for (String item : items) {
            JButton button = new JButton(item);
            button.addActionListener(e -> buyItem(item));
            panel.add(button);
        }
        
        return panel;
    }
    
    private JPanel createInventoryTab() {
        JPanel panel = new JPanel(new BorderLayout());
        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        inventoryListModel = new DefaultListModel<>();
        inventoryList = new JList<>(inventoryListModel);
        inventoryList.setFont(new Font("Monospaced", Font.PLAIN, 12));
        
        updateInventoryDisplay();
        
        panel.add(new JScrollPane(inventoryList), BorderLayout.CENTER);
        
        JButton useFertilizer = new JButton("Использовать удобрение");
        useFertilizer.addActionListener(e -> {
            player.useFertilizer(greenhouse);
            updateInventoryDisplay();
            updateGui();
        });
        panel.add(useFertilizer, BorderLayout.SOUTH);
        
        return panel;
    }
    
    private void updateInventoryDisplay() {
        inventoryListModel.clear();
        java.util.Map<String, Long> itemCounts = player.getInventory().stream()
            .collect(java.util.stream.Collectors.groupingBy(item -> item, java.util.stream.Collectors.counting()));
        
        itemCounts.entrySet().stream()
            .sorted((e1, e2) -> e1.getKey().compareTo(e2.getKey()))
            .forEach(entry -> {
                String item = entry.getKey();
                long count = entry.getValue();
                inventoryListModel.addElement(String.format("%s: %d шт.", item, count));
            });
        
        if (inventoryListModel.isEmpty()) {
            inventoryListModel.addElement("Инвентарь пуст");
        }
    }
    
    private JPanel createLogPanel() {
        JPanel panel = new JPanel(new BorderLayout());
        panel.setBorder(BorderFactory.createTitledBorder("Лог событий"));
        panel.setPreferredSize(new Dimension(0, 150));
        
        logArea = new JTextArea();
        logArea.setEditable(false);
        logArea.setFont(new Font("Monospaced", Font.PLAIN, 11));
        
        JScrollPane scrollPane = new JScrollPane(logArea);
        panel.add(scrollPane, BorderLayout.CENTER);
        
        return panel;
    }
    
    private void startGameThreads() {
        growthThread.start();
        weatherThread.start();
    }
    
    private void startGuiUpdater() {
        guiUpdateTimer = new Timer(true);
        guiUpdateTimer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                SwingUtilities.invokeLater(() -> {
                    updateGui();
                    updateInventoryDisplay();
                    checkGameOver(); // Проверяем условие поражения
                });
            }
        }, 0, 1000);
    }
    
    private void updateGui() {
        dayLabel.setText("<html><b>День:</b> " + greenhouse.getDay() + "</html>");
        moneyLabel.setText("<html><b>Деньги:</b> " + greenhouse.getMoney() + " руб.</html>");
        tempLabel.setText("<html><b>Температура:</b> " + greenhouse.getTemperature() + "°C</html>");
        humidityLabel.setText("<html><b>Влажность:</b> " + greenhouse.getHumidity() + "%</html>");
        plantCountLabel.setText("<html><b>Растений:</b> " + greenhouse.getPlantCount() + "</html>");
        
        plantListModel.clear();
        for (Plant plant : greenhouse.getPlants()) {
            String status = "";
            if (!plant.isAlive()) {
                status = "ПОГИБЛО";
            } else if (plant.isReadyToHarvest()) {
                status = "ГОТОВ К СБОРУ";
            } else if (plant.isDying()) {
                status = "КРИТИЧНОЕ СОСТОЯНИЕ";
            } else {
                status = "РАСТЕТ";
            }
            
            plantListModel.addElement(String.format("%s: рост %d%% | здоровье %d | вода %d | удобрения %d | %s",
                plant.getType(), plant.getGrowthStage(), 
                plant.getHealth(), plant.getWaterLevel(), 
                plant.getFertilizerLevel(), status));
        }
    }
    
    private void checkGameOver() {
        if (gameOver) return;
        
        if (greenhouse.getMoney() <= 0 && greenhouse.getPlants().isEmpty()) {
            gameOver = true;
            log("[ПОРАЖЕНИЕ] Вы проиграли! Закончились деньги и растения.");
            saveScore(); // Записываем рекорд
            
            int result = JOptionPane.showConfirmDialog(this,
                "Игра окончена! Ваш результат сохранен в таблице рекордов.\nВернуться в меню?",
                "Поражение",
                JOptionPane.YES_NO_OPTION);
            
            if (result == JOptionPane.YES_OPTION) {
                exitToMenu();
            }
        }
    }
    
    private void saveScore() {
        GreenhouseDatabase.saveScore(player.getName(), greenhouse, player);
        log("[РЕКОРД] Ваш результат сохранен в таблице рекордов! Счет: " + player.calculateScore());
    }
    
    public void log(String message) {
        SwingUtilities.invokeLater(() -> {
            logArea.append(message + "\n");
            logArea.setCaretPosition(logArea.getDocument().getLength());
        });
    }
    
    private void plantSeed(String plantType, int cost) {
        if (gameOver) return;

        if (player.hasSeeds(plantType)) {
            int result = JOptionPane.showConfirmDialog(this,
                "Использовать семена из инвентаря?",
                "Посадка",
                JOptionPane.YES_NO_OPTION);

            if (result == JOptionPane.YES_OPTION) {
                player.plantSeed(plantType, greenhouse);
            } else {
                buyAndPlant(plantType, cost);
            }
        } else {
            buyAndPlant(plantType, cost);
        }
        updateGui();
        updateInventoryDisplay();
    }

    private void buyAndPlant(String plantType, int cost) {
        if (gameOver) return;

        int result = JOptionPane.showConfirmDialog(this,
            "Купить семена за " + cost + " руб.?",
            "Покупка",
            JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.YES_OPTION) {
            if (player.buyItem("Семена_" + plantType, cost, greenhouse)) {
                player.plantSeed(plantType, greenhouse);
            }
        }
        updateInventoryDisplay();
    }
    
    private void waterAllPlants() {
        if (gameOver) return;
        greenhouse.waterAllPlants();
        updateGui();
    }
    
    private void fertilizeAllPlants() {
        if (gameOver) return;
        player.useFertilizer(greenhouse);
        updateGui();
        updateInventoryDisplay();
    }
    
    private void harvestAll() {
        if (gameOver) return;
        
        List<Plant> readyPlants = greenhouse.getReadyToHarvest();
        if (!readyPlants.isEmpty()) {
            int income = greenhouse.harvestAll();
            greenhouse.addMoney(income);
            player.addExperience(readyPlants.size() * 5);
        } else {
            log("[ИНФО] Нет растений готовых к сбору");
        }
        updateGui();
    }
    
    private void buyItem(String itemDesc) {
        if (gameOver) return;
        
        if (itemDesc.contains("помидора")) {
            player.buyItem("Семена_Помидор", 50, greenhouse);
        } else if (itemDesc.contains("огурца")) {
            player.buyItem("Семена_Огурец", 40, greenhouse);
        } else if (itemDesc.contains("перца")) {
            player.buyItem("Семена_Перец", 70, greenhouse);
        } else if (itemDesc.contains("салата")) {
            player.buyItem("Семена_Салат", 30, greenhouse);
        } else if (itemDesc.contains("Удобрение")) {
            player.buyItem("Удобрение", 30, greenhouse);
        } else if (itemDesc.contains("Система полива")) {
            if (greenhouse.getMoney() >= 200) {
                greenhouse.spendMoney(200);
                log("[ПОКУПКА] Установлена система полива! Растения растут быстрее.");
            }
        }
        updateGui();
        updateInventoryDisplay();
    }
    
    private void forceNextDay() {
        if (gameOver) return;
        
        log("[УСКОРЕНИЕ] Принудительный переход на следующий день");
        greenhouse.getPlants().forEach(plant -> {
            if (plant.isAlive()) {
                int currentWater = plant.getWaterLevel();
                int newWater = Math.max(0, currentWater - 10);
                plant.setWaterLevel(newWater);
                if (newWater == 0) {
                    log("[ВНИМАНИЕ] " + plant.getType() + ": вода закончилась!");
                    plant.reduceHealth(10);
                }
            }
        });
        greenhouse.getPlants().forEach(plant -> {
            if (plant.isAlive()) {
                plant.degrade();
            }
        });
        greenhouse.updatePlants();
        greenhouse.nextDay();
        log("Наступил день " + greenhouse.getDay());
        updateGui();
        updateInventoryDisplay();
    }
    
    private void saveGame() {
        if (gameOver) return;
        
        String saveName = JOptionPane.showInputDialog(this,
            "Введите название сохранения:",
            "Сохранение игры",
            JOptionPane.QUESTION_MESSAGE);
        
        if (saveName != null && !saveName.trim().isEmpty()) {
            boolean success = GreenhouseDatabase.saveGame(
                player.getName(), 
                saveName.trim(), 
                greenhouse, 
                player
            );
            
            if (success) {
                log("[СОХРАНЕНИЕ] Игра сохранена как '" + saveName + "'");
            } else {
                log("[ОШИБКА] Не удалось сохранить игру");
            }
        }
    }
    
    private void stopGame() {
        if (growthThread != null) growthThread.stopThread();
        if (weatherThread != null) weatherThread.stopThread();
        if (guiUpdateTimer != null) guiUpdateTimer.cancel();
    }
    
    private void exitToMenu() {
        if (!gameOver) {
            int result = JOptionPane.showConfirmDialog(this,
                "Сохранить игру перед выходом?",
                "Выход в меню",
                JOptionPane.YES_NO_CANCEL_OPTION);

            if (result == JOptionPane.YES_OPTION) {
                saveGame();
                saveScore();
                stopGame();
                this.dispose();
                mainFrame.setVisible(true);
            } else if (result == JOptionPane.NO_OPTION) {
                stopGame();
                this.dispose();
                mainFrame.setVisible(true);
            }
        } else {
            saveScore();
            try {
                Thread.sleep(100);
            } catch (InterruptedException ex) {}
            stopGame();
            this.dispose();
            mainFrame.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
