package greenhousesimulator.ui;

import greenhousesimulator.GreenhouseDatabase;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class MainFrame extends JFrame {
    private JButton newGameButton;
    private JButton loadGameButton;
    private JButton recordsButton;
    private JButton exitButton;
    
    public MainFrame() {
        setupUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setupUI() {
        setTitle("Тепличный симулятор");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout());
        
        JLabel titleLabel = new JLabel("ТЕПЛИЧНЫЙ СИМУЛЯТОР", SwingConstants.CENTER);
        titleLabel.setFont(new Font("Arial", Font.BOLD, 24));
        titleLabel.setBorder(BorderFactory.createEmptyBorder(30, 0, 30, 0));
        add(titleLabel, BorderLayout.NORTH);
        
        JPanel buttonPanel = new JPanel(new GridLayout(4, 1, 10, 15));
        buttonPanel.setBorder(BorderFactory.createEmptyBorder(20, 50, 50, 50));
        
        newGameButton = createStyledButton("Новая игра", new Color(46, 204, 113));
        loadGameButton = createStyledButton("Загрузить теплицу", new Color(52, 152, 219));
        recordsButton = createStyledButton("Таблица рекордов", new Color(155, 89, 182));
        exitButton = createStyledButton("Выход", new Color(231, 76, 60));
        
        buttonPanel.add(newGameButton);
        buttonPanel.add(loadGameButton);
        buttonPanel.add(recordsButton);
        buttonPanel.add(exitButton);
        
        add(buttonPanel, BorderLayout.CENTER);
        
        JLabel versionLabel = new JLabel("Версия 1.0", SwingConstants.CENTER);
        versionLabel.setFont(new Font("Arial", Font.ITALIC, 12));
        versionLabel.setBorder(BorderFactory.createEmptyBorder(10, 0, 10, 0));
        add(versionLabel, BorderLayout.SOUTH);
        
        newGameButton.addActionListener(e -> startNewGame());
        loadGameButton.addActionListener(e -> loadGame());
        recordsButton.addActionListener(e -> showRecords());
        exitButton.addActionListener(e -> System.exit(0));
        
        setSize(500, 500);
        setLocationRelativeTo(null);
    }
    
    private JButton createStyledButton(String text, Color bgColor) {
        JButton button = new JButton(text);
        button.setFont(new Font("Arial", Font.BOLD, 16));
        button.setBackground(bgColor);
        button.setForeground(Color.BLACK);
        button.setFocusPainted(false);
        button.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(bgColor.darker(), 2),
            BorderFactory.createEmptyBorder(15, 10, 15, 10)
        ));
        return button;
    }
    
    private void startNewGame() {
    String playerName = JOptionPane.showInputDialog(this, 
        "Введите ваше имя:", 
        "Новая игра", 
        JOptionPane.QUESTION_MESSAGE);
    
    if (playerName == null || playerName.trim().isEmpty()) {
        playerName = "Фермер";
    }
    
    GameWindow gameWindow = new GameWindow(playerName.trim(), this);
    gameWindow.setVisible(true);
    this.setVisible(false);
}

private void loadGame() {
    LoadGameDialog loadDialog = new LoadGameDialog(this);
    loadDialog.setVisible(true);
    
    if (loadDialog.isLoaded()) {
        GreenhouseDatabase.SaveData data = loadDialog.getLoadedData();
        String playerName = loadDialog.getPlayerName();
        
        GameWindow gameWindow = new GameWindow(playerName, data, this);
        gameWindow.setVisible(true);
        this.setVisible(false);
    }
}
    
    private void showRecords() {
        RecordsDialog recordsDialog = new RecordsDialog(this);
        recordsDialog.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
