package greenhousesimulator.ui;

import greenhousesimulator.GreenhouseDatabase;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.*;

public class RecordsDialog extends JDialog {
    private JTable recordsTable;
    private DefaultTableModel tableModel;
    
    public RecordsDialog(JFrame parent) {
        super(parent, "Таблица рекордов", true);
        setupUI();
        loadRecords();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setupUI() {
        setLayout(new BorderLayout());
        setSize(600, 400);
        setLocationRelativeTo(getParent());
        
        String[] columns = {"№", "Имя", "Счёт", "Дней", "Урожай", "Деньги"};
        tableModel = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        recordsTable = new JTable(tableModel);
        recordsTable.setFont(new Font("Arial", Font.PLAIN, 14));
        recordsTable.setRowHeight(25);
        recordsTable.getTableHeader().setFont(new Font("Arial", Font.BOLD, 14));
        
        JScrollPane scrollPane = new JScrollPane(recordsTable);
        scrollPane.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        add(scrollPane, BorderLayout.CENTER);
        
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 10, 10));
        
        JButton refreshButton = new JButton("Обновить");
        refreshButton.addActionListener(e -> loadRecords());
        
        JButton closeButton = new JButton("Закрыть");
        closeButton.addActionListener(e -> dispose());
        
        buttonPanel.add(refreshButton);
        buttonPanel.add(closeButton);
        
        add(buttonPanel, BorderLayout.SOUTH);
    }
    
    private void loadRecords() {
        tableModel.setRowCount(0);
        
        try {
            Connection conn = DriverManager.getConnection("jdbc:sqlite:greenhouse.db");
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("""
                SELECT player_name, score, day, plants_harvested, money 
                FROM scores 
                ORDER BY score DESC 
                LIMIT 10
                """);
            
            int rank = 1;
            while (rs.next()) {
                tableModel.addRow(new Object[]{
                    rank++,
                    rs.getString("player_name"),
                    rs.getInt("score"),
                    rs.getInt("day"),
                    rs.getInt("plants_harvested"),
                    rs.getInt("money") + " руб."
                });
            }
            
            conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Не удалось загрузить рекорды: " + e.getMessage(),
                "Ошибка БД",
                JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
